# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: CI
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 8, 11, 17, 19 ]
      fail-fast: false
      max-parallel: 64
    name: Test JDK ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - run: scripts/integration_test
      # https://github.com/marketplace/actions/codecov
      - run: ./mvnw -V --no-transfer-progress -P gen-code-cov clean package
      - uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
